### PR TITLE
separate thread for logging purposes

### PR DESCRIPTION
**Pull request by PeterYaoNYU**

### CODE REVIEW

**Review by dqian3 — COMMENTED** [review]
Does this preserve the semantics and features of glog? Like for example not executing VLOG statements based on the command line argument, or printing out the time of the log and such? I don't see how it does if so?

**Comment by dqian3** [comment]
Might be worth wrapping something around this: https://github.com/KjellKod/g3log

**Comment by dqian3** [comment]
Or this, which seems more popular: https://github.com/gabime/spdlog

**Comment by dqian3** [comment]
I think in general, we should make sure this is a problem first before spending too much time on adapting these libraries.

**Comment by PeterYaoNYU** [comment]
it is not like a total preservation of glog feature, but I want to make some like LOG(INFO) << works transparently without much change. There is definitely room to make it more like it. I thought about these libraries, but I do not think they work in a transparent manner. And I agree with you that I should probably first see if it is indeed the logging that causes the problem. one  way might be to print minimum log (like every 200 requests) in the reorder exp and see if the receiver bottleneck still persists.

**Comment by dqian3** [comment]
> one way might be to print minimum log (like every 200 requests) in the reorder exp and see if the receiver bottleneck still persists.

Even easier would be to just count the total number of receives in memory and discard everything else, if we can see a higher receive rate then that would indicate logging is the bottleneck.

**Comment by dqian3** [comment]
Ok, just an update based on some of the work I've been doing, it doesn't look like logging is a bottleneck in the full protocol compared to generating signatures, we can probably shelve this for now. It would be interesting to see for these specific proxy-receiver experiments though if it still is.

**Comment by dqian3** [comment]
Going to close this PR for now, as explained above.

**Pull request closed without merging**
